# Generated by Django 3.2.25 on 2024-08-29 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20240829_0512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingregients',
            new_name='ingredients',
        ),
    ]
